platform: linux/arm64

pipeline:

  gitleaks:
    image: zricethezav/gitleaks
    pull: true
    commands:
      - gitleaks --source . --verbose --redact detect

  build:
    image: registry.monotremata.xyz/static-page-builder
    pull: true
    commands:
      - make www
      - make onion

  publish:
    image: registry.monotremata.xyz/rsync
    pull: true
    settings:
      host: caladan
      user: woodpecker
      key:
        from_secret: ssh_key
      known_hosts:
        from_secret: known_hosts
      sources: ["html/www", "html/onion"]
      target: /srv/sites/frontpage
      args: --recursive --human-readable --verbose --delete

  notify:
    image: registry.monotremata.xyz/xmpp-ci
    pull: true
    settings:
      username: "woodpecker@monotremata.xyz"
      recipient: "rilla@monotremata.xyz"
      password:
        from_secret: xmpp_password
    when:
      status: [success, failure]
