platform: linux/arm64

pipeline:
  www:
    image: registry.monotremata.xyz/static-page-builder
    commands:
      - make www
      - make onion

  publish:
    image: drillster/drone-rsync
    settings:
      hosts: ["caladan"]
      user: woodpecker
      key:
        from_secret: ssh_key
      source: ./html/*
      target: /srv/sites/frontpage
      recursive: true
      delete: true
