nav:
    - name: about
      icon: info
      endpoint: ""

    - name: resume
      icon: file-text
      endpoint: resume

    - name: code
      icon: code
      url: https://git.monotremata.xyz

    - name: contact
      icon: mail
      endpoint: contact

    - name: buy me a coffee
      icon: coffee
      endpoint: donate

icon_path: icons/feather/icons
